import { createClient } from '@supabase/supabase-js'

// Ensure environment variables are defined
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl) {
  throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL environment variable')
}

if (!supabaseAnonKey) {
  throw new Error('Missing NEXT_PUBLIC_SUPABASE_ANON_KEY environment variable')
}

// Create Supabase client instance
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
})

// Server-side client for use in Server Components and Server Actions
export const createServerClient = () => {
  return createClient(supabaseUrl, supabaseAnonKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
      detectSessionInUrl: false
    }
  })
}

// Database types (will be generated by Supabase CLI)
export type Database = {
  // Add your database types here once generated
  // Example:
  // public: {
  //   Tables: {
  //     users: {
  //       Row: {
  //         id: string
  //         name: string
  //         email: string
  //         created_at: string
  //       }
  //       Insert: {
  //         id?: string
  //         name: string
  //         email: string
  //         created_at?: string
  //       }
  //       Update: {
  //         id?: string
  //         name?: string
  //         email?: string
  //         created_at?: string
  //       }
  //     }
  //   }
  // }
}